/** Generate fixed PowerShell commands embedded by the Windows installer. */

import { readFile, writeFile } from 'node:fs/promises'
import { join, resolve } from 'node:path'
import { pathToFileURL } from 'node:url'

import { REPOSITORY_ROOT } from './packaging-layout.ts'

const COMMAND_NAMES = ['COMPARE_SEMVER', 'INSPECT_SHORTCUT', 'QUERY_INSTALLED_PROCESS'] as const
type CommandName = typeof COMMAND_NAMES[number]
export type InstallerPowerShellSources = Readonly<Record<CommandName, string>>

const BUILD_ROOT = join(REPOSITORY_ROOT, 'apps/desktop/build')
const OUTPUT = join(BUILD_ROOT, 'powershell-commands.nsh')
const OWNERS: Readonly<Record<CommandName, string>> = {
  COMPARE_SEMVER: join(BUILD_ROOT, 'compare-semver.ps1'),
  INSPECT_SHORTCUT: join(BUILD_ROOT, 'inspect-shortcut.ps1'),
  QUERY_INSTALLED_PROCESS: join(BUILD_ROOT, 'query-installed-process.ps1'),
}

/** Normalize checkout-specific line endings and retain exactly one final newline. */
export function canonicalPowerShellSource(source: string): string {
  return `${source.replace(/\r\n?/gu, '\n').replace(/\n+$/u, '')}\n`
}

/** Render the deterministic NSIS definitions for fixed PowerShell commands. */
export function renderInstallerPowerShellCommands(sources: InstallerPowerShellSources): string {
  const definitions = COMMAND_NAMES.map((name) => {
    const encoded = Buffer.from(canonicalPowerShellSource(sources[name]), 'utf16le').toString('base64')
    return `!define DSH_POWERSHELL_${name} "${encoded}"`
  })
  return `; Generated by scripts/desktop/generate-installer-powershell.ts. Do not edit.\n${definitions.join('\n')}\n`
}

/** Parse the complete generated NSIS command map. */
export function parseInstallerPowerShellCommands(source: string): Record<CommandName, string> {
  const commands = {} as Record<CommandName, string>
  for (const name of COMMAND_NAMES) {
    const match = source.match(new RegExp(`^!define DSH_POWERSHELL_${name} \"(?<encoded>[A-Za-z0-9+/=]+)\"$`, 'mu'))
    if (match?.groups?.encoded === undefined) throw new Error(`desktop packaging: missing PowerShell command ${name}`)
    commands[name] = match.groups.encoded
  }
  return commands
}

/** Reject a generated include that does not exactly represent its owner scripts. */
export function assertInstallerPowerShellCommandsFresh(
  generated: string,
  sources: InstallerPowerShellSources,
): void {
  parseInstallerPowerShellCommands(generated)
  if (generated !== renderInstallerPowerShellCommands(sources)) {
    throw new Error('desktop packaging: generated PowerShell commands are stale')
  }
}

/** Read the fixed PowerShell owner scripts. */
export async function readInstallerPowerShellSources(): Promise<InstallerPowerShellSources> {
  return {
    COMPARE_SEMVER: await readFile(OWNERS.COMPARE_SEMVER, 'utf8'),
    INSPECT_SHORTCUT: await readFile(OWNERS.INSPECT_SHORTCUT, 'utf8'),
    QUERY_INSTALLED_PROCESS: await readFile(OWNERS.QUERY_INSTALLED_PROCESS, 'utf8'),
  }
}

/** Verify the checked-in generated include before packaging. */
export async function verifyInstallerPowerShellCommands(): Promise<void> {
  assertInstallerPowerShellCommandsFresh(await readFile(OUTPUT, 'utf8'), await readInstallerPowerShellSources())
}

async function main(): Promise<void> {
  await writeFile(OUTPUT, renderInstallerPowerShellCommands(await readInstallerPowerShellSources()), 'utf8')
}

const invokedPath = process.argv[1]
if (invokedPath !== undefined && pathToFileURL(resolve(invokedPath)).href === import.meta.url) {
  try { await main() } catch (error: unknown) {
    console.error(error instanceof Error ? error.message : error)
    process.exitCode = 1
  }
}
