/** Adapt pinned electron-builder uninstall file operations for Windows extended-length paths. */
import { createHash } from 'node:crypto'
import { readFile, writeFile } from 'node:fs/promises'
import { createRequire } from 'node:module'
import { dirname, join, resolve } from 'node:path'
import { pathToFileURL } from 'node:url'
import { REPOSITORY_ROOT } from './packaging-layout.ts'

const OUTPUT = join(REPOSITORY_ROOT, 'apps/desktop/build/uninstall-files.nsh')
const REVIEWED_TEMPLATE_SHA256 = '9ee2dac4593478083e8aa6f8487287ce9401006ccd50ecc538871d133ea4a42c'

/**
 * Preserve the reviewed upstream relocation and rollback algorithms with extended-length file paths.
 * @param template - Pinned electron-builder uninstaller source.
 * @returns NSIS functions and the custom file-removal hook.
 */
export function renderInstallerFileOperations(template: string): string {
  const canonical = template.replace(/\r\n?/gu, '\n')
  if (createHash('sha256').update(canonical).digest('hex') !== REVIEWED_TEMPLATE_SHA256) {
    throw new Error('desktop packaging: review changed electron-builder uninstall file operations before regenerating')
  }
  const functions = canonical.slice(canonical.indexOf('Function un.atomicRMDir'), canonical.indexOf('!ifndef UNINSTALL_SECTION_NAME'))
    .replaceAll('un.atomicRMDir', 'un.DshAtomicRMDir')
    .replaceAll('un.restoreFiles', 'un.DshRestoreFiles')
    .replaceAll('$INSTDIR', '$DshInstallFilesRoot')
    .replaceAll('$PLUGINSDIR\\old-install', '$DshStagedFilesRoot')
  return `; Generated by scripts/desktop/generate-installer-file-operations.ts. Do not edit.
; File relocation and rollback adapted from electron-builder (MIT).
; Copyright (c) 2015 Loopline Systems
;
; Permission is hereby granted, free of charge, to any person obtaining a copy
; of this software and associated documentation files (the "Software"), to deal
; in the Software without restriction, including without limitation the rights
; to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
; copies of the Software, and to permit persons to whom the Software is
; furnished to do so, subject to the following conditions:
;
; The above copyright notice and this permission notice shall be included in all
; copies or substantial portions of the Software.
;
; THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
; IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
; FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
; AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
; LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
; OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
; SOFTWARE.
!ifdef BUILD_UNINSTALLER
Var DshInstallFilesRoot
Var DshStagedFilesRoot

!macro DshExtendedPath Input Output
  StrCpy \${Output} "\${Input}" 4
  \${If} \${Output} == "\\\\?\\"
    StrCpy \${Output} "\${Input}"
  \${Else}
    StrCpy \${Output} "\${Input}" 2
    \${If} \${Output} == "\\\\"
      StrCpy \${Output} "\${Input}" "" 2
      StrCpy \${Output} "\\\\?\\UNC\\\${Output}"
    \${Else}
      StrCpy \${Output} "\\\\?\\\${Input}"
    \${EndIf}
  \${EndIf}
!macroend

!macro DshUninstallFileFunctions
${functions}!macroend

!macro customRemoveFiles
  !insertmacro DshExtendedPath "$INSTDIR" $DshInstallFilesRoot
  !insertmacro DshExtendedPath "$PLUGINSDIR\\old-install" $DshStagedFilesRoot
  \${If} \${isUpdated}
    CreateDirectory "$DshStagedFilesRoot"
    Push ""
    Call un.DshAtomicRMDir
    Pop $R0
    \${If} $R0 != 0
      !insertmacro DshE2eTrace "update relocation failed: $R0"
      Push ""
      Call un.DshRestoreFiles
      Pop $R0
      Abort "Unable to relocate the previous installation."
    \${EndIf}
  \${EndIf}
  SetOutPath $TEMP
  RMDir /r "$DshInstallFilesRoot"
!macroend
!endif
`
}

/** Read the template through the desktop package's declared electron-builder dependency. */
export async function readInstallerFileOperationsTemplate(): Promise<string> {
  const desktopRequire = createRequire(join(REPOSITORY_ROOT, 'apps/desktop/package.json'))
  const builder = desktopRequire.resolve('electron-builder/package.json')
  const library = createRequire(builder).resolve('app-builder-lib/package.json')
  return readFile(join(dirname(library), 'templates/nsis/uninstaller.nsh'), 'utf8')
}

/** Reject stale generated uninstall operations before building an installer. */
export async function verifyInstallerFileOperations(): Promise<void> {
  if (await readFile(OUTPUT, 'utf8') !== renderInstallerFileOperations(await readInstallerFileOperationsTemplate())) {
    throw new Error('desktop packaging: generated uninstall file operations are stale')
  }
}

const invokedPath = process.argv[1]
if (invokedPath !== undefined && pathToFileURL(resolve(invokedPath)).href === import.meta.url) {
  await writeFile(OUTPUT, renderInstallerFileOperations(await readInstallerFileOperationsTemplate()), 'utf8')
}
