import { defineConfig } from 'tsdown'

export default defineConfig([
  {
    entry: { main: 'lib/types/main.js' },
    outDir: 'lib',
    format: ['esm'],
    platform: 'node',
    target: 'es2024',
    fixedExtension: false,
    dts: false,
    clean: false,
    deps: { neverBundle: ['electron'] },
  },
  {
    entry: { preload: 'lib/types/preload.js' },
    outDir: 'lib',
    format: ['cjs'],
    platform: 'node',
    target: 'es2024',
    fixedExtension: false,
    dts: false,
    clean: false,
    deps: { neverBundle: ['electron'] },
    outputOptions: { codeSplitting: false },
  },
  {
    entry: { 'startup-preload': 'lib/types/startup-preload.js' },
    outDir: 'lib',
    format: ['cjs'],
    platform: 'node',
    target: 'es2024',
    fixedExtension: false,
    dts: false,
    clean: false,
    deps: { neverBundle: ['electron'] },
    outputOptions: { codeSplitting: false },
  },
  {
    entry: { 'startup-renderer': 'lib/types/startup-renderer.js' },
    outDir: 'lib',
    format: ['esm'],
    platform: 'browser',
    target: 'es2024',
    fixedExtension: false,
    dts: false,
    clean: false,
    outputOptions: { codeSplitting: false },
  },
])
